#!/bin/bash
#
#SBATCH --job-name=data_prep
#SBATCH --output=logsprepdata/test_%j.txt  # output file
#SBATCH -e logsprepdata/test_%j.err        # File to which STDERR will be written
#SBATCH --gres=gpu:1
#SBATCH --partition=1080ti-short # Partition to submit to
#SBATCH --mem=40000
#
#SBATCH --ntasks=1

# change num_buckets (4: wlp, 8: matsci)

mkdir -p $mnt/preprocessed_materials
for k in 1 2 5 10 15 20 30 40 50; do
        python copy_model/prepare_context_k.py /mnt/nfs/work1/mccallum/abajaj/akbc/data/materials-scibert-retr/original.annoy original_bert.pkl /mnt/nfs/work1/mccallum/abajaj/akbc/data/materials-scibert-retr/train_embeddings.pkl /mnt/nfs/work1/mccallum/abajaj/akbc/data/materials-scibert-retr/test_embeddings.pkl $mnt/preprocessed_materials/testk${k}.pkl scibert 8 ${k}
        python copy_model/prepare_context_k.py /mnt/nfs/work1/mccallum/abajaj/akbc/data/materials-scibert-retr/original.annoy original_bert.pkl /mnt/nfs/work1/mccallum/abajaj/akbc/data/materials-scibert-retr/train_embeddings.pkl /mnt/nfs/work1/mccallum/abajaj/akbc/data/materials-scibert-retr/val_embeddings.pkl $mnt/preprocessed_materials/valk${k}.pkl scibert 8 ${k}
done
	
# python copy_model/prepare_context_k.py /mnt/nfs/work1/mccallum/abajaj/akbc/data/materials-scibert-retr/original.annoy original_bert.pkl /mnt/nfs/work1/mccallum/abajaj/akbc/data/materials-scibert-retr/train_embeddings.pkl /mnt/nfs/work1/mccallum/abajaj/akbc/data/materials-scibert-retr/test_embeddings.pkl /mnt/nfs/work1/mccallum/abajaj/akbc/data/materials-scibert-retr/exp_k/testk1.pkl scibert 8 1
# python copy_model/prepare_context_k.py /mnt/nfs/work1/mccallum/abajaj/akbc/data/materials-scibert-retr/original.annoy original_bert.pkl /mnt/nfs/work1/mccallum/abajaj/akbc/data/materials-scibert-retr/train_embeddings.pkl /mnt/nfs/work1/mccallum/abajaj/akbc/data/materials-scibert-retr/test_embeddings.pkl /mnt/nfs/work1/mccallum/abajaj/akbc/data/materials-scibert-retr/exp_k/testk2.pkl scibert 8 2
# python copy_model/prepare_context_k.py /mnt/nfs/work1/mccallum/abajaj/akbc/data/materials-scibert-retr/original.annoy original_bert.pkl /mnt/nfs/work1/mccallum/abajaj/akbc/data/materials-scibert-retr/train_embeddings.pkl /mnt/nfs/work1/mccallum/abajaj/akbc/data/materials-scibert-retr/test_embeddings.pkl /mnt/nfs/work1/mccallum/abajaj/akbc/data/materials-scibert-retr/exp_k/testk5.pkl scibert 8 5
# python copy_model/prepare_context_k.py /mnt/nfs/work1/mccallum/abajaj/akbc/data/materials-scibert-retr/original.annoy original_bert.pkl /mnt/nfs/work1/mccallum/abajaj/akbc/data/materials-scibert-retr/train_embeddings.pkl /mnt/nfs/work1/mccallum/abajaj/akbc/data/materials-scibert-retr/test_embeddings.pkl /mnt/nfs/work1/mccallum/abajaj/akbc/data/materials-scibert-retr/exp_k/testk10.pkl scibert 8 10
# python copy_model/prepare_context_k.py /mnt/nfs/work1/mccallum/abajaj/akbc/data/materials-scibert-retr/original.annoy original_bert.pkl /mnt/nfs/work1/mccallum/abajaj/akbc/data/materials-scibert-retr/train_embeddings.pkl /mnt/nfs/work1/mccallum/abajaj/akbc/data/materials-scibert-retr/test_embeddings.pkl /mnt/nfs/work1/mccallum/abajaj/akbc/data/materials-scibert-retr/exp_k/testk15.pkl scibert 8 15
# python copy_model/prepare_context_k.py /mnt/nfs/work1/mccallum/abajaj/akbc/data/materials-scibert-retr/original.annoy original_bert.pkl /mnt/nfs/work1/mccallum/abajaj/akbc/data/materials-scibert-retr/train_embeddings.pkl /mnt/nfs/work1/mccallum/abajaj/akbc/data/materials-scibert-retr/test_embeddings.pkl /mnt/nfs/work1/mccallum/abajaj/akbc/data/materials-scibert-retr/exp_k/testk20.pkl scibert 8 20
# python copy_model/prepare_context_k.py /mnt/nfs/work1/mccallum/abajaj/akbc/data/materials-scibert-retr/original.annoy original_bert.pkl /mnt/nfs/work1/mccallum/abajaj/akbc/data/materials-scibert-retr/train_embeddings.pkl /mnt/nfs/work1/mccallum/abajaj/akbc/data/materials-scibert-retr/test_embeddings.pkl /mnt/nfs/work1/mccallum/abajaj/akbc/data/materials-scibert-retr/exp_k/testk30.pkl scibert 8 30
# python copy_model/prepare_context_k.py /mnt/nfs/work1/mccallum/abajaj/akbc/data/materials-scibert-retr/original.annoy original_bert.pkl /mnt/nfs/work1/mccallum/abajaj/akbc/data/materials-scibert-retr/train_embeddings.pkl /mnt/nfs/work1/mccallum/abajaj/akbc/data/materials-scibert-retr/test_embeddings.pkl /mnt/nfs/work1/mccallum/abajaj/akbc/data/materials-scibert-retr/exp_k/testk40.pkl scibert 8 40
# python copy_model/prepare_context_k.py /mnt/nfs/work1/mccallum/abajaj/akbc/data/materials-scibert-retr/original.annoy original_bert.pkl /mnt/nfs/work1/mccallum/abajaj/akbc/data/materials-scibert-retr/train_embeddings.pkl /mnt/nfs/work1/mccallum/abajaj/akbc/data/materials-scibert-retr/test_embeddings.pkl /mnt/nfs/work1/mccallum/abajaj/akbc/data/materials-scibert-retr/exp_k/testk50.pkl scibert 8 50
# 
# python copy_model/prepare_context_k.py /mnt/nfs/work1/mccallum/abajaj/akbc/data/materials-scibert-retr/original.annoy original_bert.pkl /mnt/nfs/work1/mccallum/abajaj/akbc/data/materials-scibert-retr/train_embeddings.pkl /mnt/nfs/work1/mccallum/abajaj/akbc/data/materials-scibert-retr/val_embeddings.pkl /mnt/nfs/work1/mccallum/abajaj/akbc/data/materials-scibert-retr/exp_k/valk1.pkl scibert 8 1
# python copy_model/prepare_context_k.py /mnt/nfs/work1/mccallum/abajaj/akbc/data/materials-scibert-retr/original.annoy original_bert.pkl /mnt/nfs/work1/mccallum/abajaj/akbc/data/materials-scibert-retr/train_embeddings.pkl /mnt/nfs/work1/mccallum/abajaj/akbc/data/materials-scibert-retr/val_embeddings.pkl /mnt/nfs/work1/mccallum/abajaj/akbc/data/materials-scibert-retr/exp_k/valk2.pkl scibert 8 2
# python copy_model/prepare_context_k.py /mnt/nfs/work1/mccallum/abajaj/akbc/data/materials-scibert-retr/original.annoy original_bert.pkl /mnt/nfs/work1/mccallum/abajaj/akbc/data/materials-scibert-retr/train_embeddings.pkl /mnt/nfs/work1/mccallum/abajaj/akbc/data/materials-scibert-retr/val_embeddings.pkl /mnt/nfs/work1/mccallum/abajaj/akbc/data/materials-scibert-retr/exp_k/valk5.pkl scibert 8 5
# python copy_model/prepare_context_k.py /mnt/nfs/work1/mccallum/abajaj/akbc/data/materials-scibert-retr/original.annoy original_bert.pkl /mnt/nfs/work1/mccallum/abajaj/akbc/data/materials-scibert-retr/train_embeddings.pkl /mnt/nfs/work1/mccallum/abajaj/akbc/data/materials-scibert-retr/val_embeddings.pkl /mnt/nfs/work1/mccallum/abajaj/akbc/data/materials-scibert-retr/exp_k/valk10.pkl scibert 8 10
# python copy_model/prepare_context_k.py /mnt/nfs/work1/mccallum/abajaj/akbc/data/materials-scibert-retr/original.annoy original_bert.pkl /mnt/nfs/work1/mccallum/abajaj/akbc/data/materials-scibert-retr/train_embeddings.pkl /mnt/nfs/work1/mccallum/abajaj/akbc/data/materials-scibert-retr/val_embeddings.pkl /mnt/nfs/work1/mccallum/abajaj/akbc/data/materials-scibert-retr/exp_k/valk15.pkl scibert 8 15
# python copy_model/prepare_context_k.py /mnt/nfs/work1/mccallum/abajaj/akbc/data/materials-scibert-retr/original.annoy original_bert.pkl /mnt/nfs/work1/mccallum/abajaj/akbc/data/materials-scibert-retr/train_embeddings.pkl /mnt/nfs/work1/mccallum/abajaj/akbc/data/materials-scibert-retr/val_embeddings.pkl /mnt/nfs/work1/mccallum/abajaj/akbc/data/materials-scibert-retr/exp_k/valk20.pkl scibert 8 20
# python copy_model/prepare_context_k.py /mnt/nfs/work1/mccallum/abajaj/akbc/data/materials-scibert-retr/original.annoy original_bert.pkl /mnt/nfs/work1/mccallum/abajaj/akbc/data/materials-scibert-retr/train_embeddings.pkl /mnt/nfs/work1/mccallum/abajaj/akbc/data/materials-scibert-retr/val_embeddings.pkl /mnt/nfs/work1/mccallum/abajaj/akbc/data/materials-scibert-retr/exp_k/valk30.pkl scibert 8 30
# python copy_model/prepare_context_k.py /mnt/nfs/work1/mccallum/abajaj/akbc/data/materials-scibert-retr/original.annoy original_bert.pkl /mnt/nfs/work1/mccallum/abajaj/akbc/data/materials-scibert-retr/train_embeddings.pkl /mnt/nfs/work1/mccallum/abajaj/akbc/data/materials-scibert-retr/val_embeddings.pkl /mnt/nfs/work1/mccallum/abajaj/akbc/data/materials-scibert-retr/exp_k/valk40.pkl scibert 8 40
# python copy_model/prepare_context_k.py /mnt/nfs/work1/mccallum/abajaj/akbc/data/materials-scibert-retr/original.annoy original_bert.pkl /mnt/nfs/work1/mccallum/abajaj/akbc/data/materials-scibert-retr/train_embeddings.pkl /mnt/nfs/work1/mccallum/abajaj/akbc/data/materials-scibert-retr/val_embeddings.pkl /mnt/nfs/work1/mccallum/abajaj/akbc/data/materials-scibert-retr/exp_k/valk50.pkl scibert 8 50
